spring:
  cloud:
    gateway:
      routes:
        - id: catalogo-route
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/categorias/**
        - id: catalogo-instancia
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/catalogo/instancia
        - id: catalogo-swagger
          uri: lb://catalogo
          predicates:
            - Path=/catalogo/swagger-ui/**,/catalogo/v3/api-docs/**
          filters:
            - StripPrefix=1
        
        # PRODUCTO
        - id: producto-route
          uri: lb://producto
          predicates:
            - Path=/api/v1/productos/**
        - id: producto-instancia
          uri: lb://producto
          predicates:
            - Path=/api/v1/producto/instancia
        - id: producto-swagger
          uri: lb://producto
          predicates:
            - Path=/producto/swagger-ui/**,/producto/v3/api-docs/**
          filters:
            - StripPrefix=1
        # AUTH
        - id: auth-route
          uri: lb://auth
          predicates:
            - Path=/api/v1/usuarios/**
        - id: auth-instancia
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/instancia
        - id: auth-swagger
          uri: lb://auth
          predicates:
            - Path=/auth/swagger-ui/**,/auth/v3/api-docs/**
          filters:
            - StripPrefix=1

        # CANCHAS
        - id: canchas-route
          uri: lb://canchas
          predicates:
            - Path=/api/v1/canchas/**
        - id: canchas-instancia
          uri: lb://canchas
          predicates:
            - Path=/api/v1/canchas/instancia
        - id: canchas-swagger
          uri: lb://canchas
          predicates:
            - Path=/canchas/swagger-ui/**,/canchas/v3/api-docs/**
          filters:
            - StripPrefix=1

        # HORARIOS
        - id: horarios-route
          uri: lb://horarios
          predicates:
            - Path=/api/v1/horarios/**
        - id: horarios-instancia
          uri: lb://horarios
          predicates:
            - Path=/api/v1/horario/instancia
        - id: horarios-swagger
          uri: lb://horarios
          predicates:
            - Path=/horarios/swagger-ui/**,/horarios/v3/api-docs/**
          filters:
            - StripPrefix=1

        # RESERVAS
        - id: reservas-route
          uri: lb://reservas
          predicates:
            - Path=/api/v1/reservas/**
        - id: reservas-instancia
          uri: lb://reservas
          predicates:
            - Path=/api/v1/reserva/instancia
        - id: reservas-swagger
          uri: lb://reservas
          predicates:
            - Path=/reservas/swagger-ui/**,/reservas/v3/api-docs/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"